version: '3.8'
services:
  node_server:
    build: .
    container_name: backend_server
    restart: always
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - redis
      - rabbitmq
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: redis_cache
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]
    volumes:
      - redis_volume_data:/redis_data
  redis_insights:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insights_volume_data:/redis_insights_data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"   # Default RabbitMQ messaging port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/rabbitmq_data
volumes:
  redis_volume_data:
  redis_insights_volume_data:
  rabbitmq_data: