version: '3.8'
services:
  backend:
    build: .
    ports:
      - 5000:5000
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]
  redis_insights:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insights_volume_data:/db
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"   # Default RabbitMQ messaging port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: SmicGames
      RABBITMQ_DEFAULT_PASS: SmicGames
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  redis_volume_data:
  redis_insights_volume_data:
  rabbitmq_data: